#!/bin/bash

main(){
	person=$(root)
	adb shell "$1" || person=$(user)
	echo $person | base64 -d > /tmp/into_adb_shell.expect && expect /tmp/into_adb_shell.expect
}

user(){
	echo "IyEvdXNyL2Jpbi9leHBlY3QKCnNldCB0aW1lb3V0IDIKc2V0IHBhdGggIi9kYXRhL2xvY2FsL3RtcCIKc3Bhd24gYWRiIHNoZWxsCgpleHBlY3QgIiokICIge3NlbmQgImNkICRwYXRoXG4ifQpleHBlY3QgIiokcGF0aCAkICIge3NlbmQgImlkXG4ifQpleHBlY3QgIiokcGF0aCAkICIge3NlbmQgIlBTMT0nJCAnXG4ifQpleHBlY3QgIiQgIiB7c2VuZCAiYWxpYXMgY2w9Y2xlYXJcbiJ9CmV4cGVjdCAiJCAiIHtzZW5kICJhbGlhcyBscz0nbHMgLS1jb2xvcidcbiJ9CmV4cGVjdCAiJCAiIHtzZW5kICJhbGlhcyBsbD0nbHMgLWxGaCAtLWNvbG9yJ1xuIn0KZXhwZWN0ICIkICIge3NlbmQgImFsaWFzIGR1PSdkdSAtc2gnXG4ifQpleHBlY3QgIiQgIiB7c2VuZCAiY2wmJnB3ZFxuIn0KCmludGVyYWN0Cg=="
}

root(){
	echo "IyEvdXNyL2Jpbi9leHBlY3QKCnNldCB0aW1lb3V0IDIKc2V0IHBhdGggIi9kYXRhL2xvY2FsL3RtcCIKc3Bhd24gYWRiIHNoZWxsCgpleHBlY3QgIiokICIge3NlbmQgInN1XG4ifQpleHBlY3QgIiojICIge3NlbmQgImNkICRwYXRoXG4ifQpleHBlY3QgIiojICIge3NlbmQgIi4vYmFzaFxuIn0KZXhwZWN0ICIqIiB7c2VuZCAiUFMxPScjICdcbiJ9CmV4cGVjdCAiKiIge3NlbmQgImFsaWFzIGNsPWNsZWFyXG4ifQpleHBlY3QgIioiIHtzZW5kICJhbGlhcyBscz0nbHMgLS1jb2xvcidcbiJ9CmV4cGVjdCAiKiIge3NlbmQgImFsaWFzIGxsPSdscyAtbEZoIC0tY29sb3InXG4ifQpleHBlY3QgIioiIHtzZW5kICJhbGlhcyBkdT0nZHUgLXNoJ1xuIn0KZXhwZWN0ICIqIiB7c2VuZCAiY2wmJnB3ZFxuIn0KCmludGVyYWN0Cg=="
	#Update -> PS1 : #
	#echo "IyEvdXNyL2Jpbi9leHBlY3QKCnNldCB0aW1lb3V0IDIKc2V0IHBhdGggIi9kYXRhL2xvY2FsL3RtcCIKc3Bhd24gYWRiIHNoZWxsCgpleHBlY3QgIiokICIge3NlbmQgInN1XG4ifQpleHBlY3QgIiojICIge3NlbmQgImNkICRwYXRoXG4ifQpleHBlY3QgIiojICIge3NlbmQgIi4vYmFzaFxuIn0KZXhwZWN0ICIqIiB7c2VuZCAiaWRcbiJ9CmV4cGVjdCAiKiIge3NlbmQgImFsaWFzIGNsPWNsZWFyXG4ifQpleHBlY3QgIioiIHtzZW5kICJhbGlhcyBscz0nbHMgLS1jb2xvcidcbiJ9CmV4cGVjdCAiKiIge3NlbmQgImFsaWFzIGxsPSdscyAtbEZoIC0tY29sb3InXG4ifQpleHBlY3QgIioiIHtzZW5kICJhbGlhcyBkdT0nZHUgLXNoJ1xuIn0KZXhwZWN0ICIqIiB7c2VuZCAiY2wmJnB3ZFxuIn0KCmludGVyYWN0Cg=="
}

main "su -c 'id'"
