#!/bin/bash
#adb shell dumpsys activity top | grep ACTIVITY #显示当前栈的Activity
# Output:
#  ACTIVITY com.android.settings/.HWSettings 9a09459 pid=13293
#  ACTIVITY com.termux/.app.TermuxActivity a986888 pid=3927
#  ACTIVITY bin.mt.plus/l.ۤۜۜ 6796e1c pid=7354
#  ACTIVITY com.huawei.android.launcher/.unihome.UniHomeLauncher 8b0ab94 pid=2768
#  ACTIVITY com.google.android.apps.books/com.google.android.apps.play.books.home.HomeActivity 88e3219 pid=26284

adb shell dumpsys window | grep  mCurrentFocus | awk '{print $3}' | sed 's/}//'
# Output:
#  mCurrentFocus=Window{a501fd9 u0 com.google.android.apps.books/com.google.android.apps.play.books.home.HomeActivity}


