#!/bin/bash

set -e

IP=$(adb -d shell ifconfig wlan0 2>&1 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')

if [ -s "$IP" ]; then
	echo -e "\033[31mUnable to find the device\033[0m"
	exit
fi

adb -d tcpip 5555 && adb -d connect $IP:5555
