#!/bin/bash

set -e

#targetpath="/sdcard"
targetpath="/data/local/tmp"
adb="adb"

main() {
	local obj="$1"
	local path="$2"

	if [ -z "$obj" ]; then
		echo -e "\033[31m Try --help\033[0m"
		exit 1
	fi

	if [ $path ]; then targetpath="$path"; fi

	# 本地存在则为推送
	if [[ -f "$obj" || -d "$obj" ]]; then
		echo adb push $obj ${targetpath}/
		adb push $obj ${targetpath}/

	# 本地不存在则为拉取
	else
		echo adb pull ${targetpath}/$obj $obj
		adb pull ${targetpath}/$obj $obj
	fi
}

usage() {
	echo "Usage :  $(basename "$0") [options] [--] cp-file cp-path($targetpath)

	Options:
	-h, --help                  Display this message
	-p, --posix                 Posix model parse shell command
	-v, --version               Display script version
	-d                          Use usb device
	-e                          Use network device"

}

while getopts ":hdevf:D:-:" opt; do
	case "${opt}" in
	h) usage && exit 0 ;;
	d) adb="adb -d" ;;
	e) adb="adb -e" ;;
	v)
		echo "$0 -- Version $ScriptVersion"
		exit
		;;
	f) file=${OPTARG} ;;
	D) directory=${OPTARG} ;;
	-) case "${OPTARG}" in
		help) usage && exit 0 ;;
		debug) set -x ;;
		posix) set -o posix ;;
		version)
			echo "$0 -- Version $ScriptVersion"
			exit
			;;
		file)
			file=${!OPTIND}
			OPTIND=$((OPTIND + 1))
			;;
		directory)
			directory=${!OPTIND}
			OPTIND=$((OPTIND + 1))
			;;
		*) echo "Invalid option: --${OPTARG}" >&2 && exit 1 ;;
		esac ;;
	:) echo "Option -${OPTARG} requires an argument." >&2 && exit 1 ;;
	*) echo "Invalid option: -${OPTARG}" >&2 && exit 1 ;;
	esac
done
shift $((OPTIND - 1))

main "$@"
