#!/bin/bash

set -e

#docker_id="/sdcard"
docker_id="/data/local/tmp"
adb="adb"

main() {
	local one_obj="$1"
	local two_obj="$2"

	if [ -z "$one_obj" ]; then
		echo -e "\033[31m Try --help\033[0m"
		exit
	fi

	if [[ -f "$one_obj" || -d "$one_obj" ]]; then
		local_tar="$one_obj"
		docker_tar="${docker_id}/${two_obj}"
		if [ -z "$two_obj" ]; then
			docker_tar="${docker_id}/${user}"
		fi
		echo "adb push \"$local_tar\" \"$docker_tar\""
		adb push "$local_tar" "$docker_tar"
	else
		docker_tar="${docker_id}/${one_obj}"
		local_tar="$two_obj"
		if [ -z "$two_obj" ]; then
			local_tar="./"
		fi
		echo "adb pull \"$docker_tar\" \"$local_tar\""
		adb pull "$docker_tar" "$local_tar"
	fi
}

usage() {
	echo "Usage :  $(basename "$0") [options] [--] argument-1 argument-2

  Options:
  -h, --help                  Display this message
  -d, --debug                 Debug model run
  -p, --posix                 Posix model parse shell command
  -v, --version               Display script version
  -f, --file FILE             Target file 
  -D, --directory DIRECTORY   Target directory"

}

while getopts ":hdevf:D:-:" opt; do
	case "${opt}" in
	h) usage && exit 0 ;;
	d) adb="adb -d" ;;
	e) adb="adb -e" ;;
	v)
		echo "$0 -- Version $ScriptVersion"
		exit
		;;
	f) file=${OPTARG} ;;
	D) directory=${OPTARG} ;;
	-) case "${OPTARG}" in
		help) usage && exit 0 ;;
		debug) set -x ;;
		posix) set -o posix ;;
		version)
			echo "$0 -- Version $ScriptVersion"
			exit
			;;
		file)
			file=${!OPTIND}
			OPTIND=$((OPTIND + 1))
			;;
		directory)
			directory=${!OPTIND}
			OPTIND=$((OPTIND + 1))
			;;
		*) echo "Invalid option: --${OPTARG}" >&2 && exit 1 ;;
		esac ;;
	:) echo "Option -${OPTARG} requires an argument." >&2 && exit 1 ;;
	*) echo "Invalid option: -${OPTARG}" >&2 && exit 1 ;;
	esac
done
shift $((OPTIND - 1))

main "$@"
