#!/bin/bash

main() {
	#adb shell "/data/local/tmp/.bash --version" || install_bash
	person=$(root)
	if [ ! $(adb shell 'id -u') == '0' ]; then #进入shell即为非root的情况
		adb shell "$1" || person=$(user)          #再次检测su是否成功提权，否则为普通用户
	fi
	expect /tmp/into_adb_shell.expect
}

install_bash() {
	version="5.2.015-1.2.3-2"

	abi=$(adb shell getprop ro.product.cpu.abi)
	if [ "$abi" == "arm64-v8a" ]; then
		abi="aarch64"
	elif [ "$abi" == "x86_64" ]; then
		abi="x86_64"
	fi

	if [ ! -f "/tmp/bash-linux-${abi}" ]; then
		wget https://github.com/robxu9/bash-static/releases/download/${version}/bash-linux-${abi} -O /tmp/bash-linux-${abi}
	fi

	adb push /tmp/bash-linux-${abi} /data/local/tmp/.bash
	adb shell "chmod +x /data/local/tmp/.bash"
}

user() {
	echo "TODO user!"
	exit
}

root() {
	cat <<EOF >/tmp/into_adb_shell.expect
set timeout 2
set path "/data/local/tmp"
spawn adb shell

expect "*$ " {send "su\n"}
expect "*# " {send "\$path/.bash\n"}
expect "*" {send "PS1='\$ '\n"}
expect "*" {send "export HOME=\$path\n"}
expect "*" {send "alias cl=clear\n"}
expect "*" {send "alias ls='ls --color'\n"}
expect "*" {send "alias ll='ls -lFh --color'\n"}
expect "*" {send "alias du='du -sh'\n"}
expect "*" {send "cd&&./termux.sh\n"}
expect "*" {send "cd&&cl&&pwd\n"}

interact
EOF
}

main "su -c 'id'"
