#!/bin/bash

set -e

if [ ! $1 ]; then
	echo -e "\033[31mA port needs to be specified!\033[0m"
	exit 1
fi

port="$1"

#echo "lsof:"
sudo lsof -i :$port

#echo "netstat:"
#sudo netstat -tulnp | grep :$port
