#!/bin/bash

list=(*.lof *.lot *.aux *.fdb_latexmk *.fls *.log *.out *.synctex.gz *.toc *.xdv *.synctex\(busy\))

date=$(date +"%Y%m%d%H%M%S")
sum=0
for i in ${list[*]};do
	if [ -f $i ];then
		mv $i /tmp/${date}-$i
		((sum++))
	fi
done

if [ $sum == 0 ];then
	echo -e "\033[31mNo the Tex files to be cleaned up were found\033[0m"
else
	echo -e "\033[32mok!\033[0m"
fi

