#!/bin/bash

rtsp_ip="$1"

if [[ ! "$rtsp_ip" =~ "rtsp://" ]];then
	echo -e "\033[31m$0 rtsp://127.0.0.1:8888/live/test output.mp4 ?\033[0m";exit
fi

out_file="$2"

if [ ! $out_file ];then
	echo -e "\033[31m$0 rtsp://127.0.0.1:8888/live/test output.mp4 ?\033[0m";exit
fi

ffmpeg -rtsp_transport tcp -i $rtsp_ip -c copy $out_file
