#!/bin/bash

#rtsp_ip="$1"

#check
#if [[ ! "$rtsp_ip" =~ "rtsp://" ]];then
#	echo -e "\033[31m$0 rtsp://127.0.0.1:8888/live/test?\033[0m";exit
#fi

input=$1 # 获取输入参数

# 用正则表达式匹配IP:Port格式
# ^ 开始符
# ([0-9]{1,3}\.){3}[0-9]{1,3} 匹配IP地址，例如127.0.0.1
# : 分号，端口的前缀
# [0-9]+ 匹配端口号
# $ 结束符
regex="^([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]+"

if [[ $input =~ $regex ]]; then
	echo "ffplay -rtsp_transport tcp "rtsp://$input""
	ffplay -rtsp_transport tcp "rtsp://$input"
else
	ffplay -rtsp_transport tcp "$input"
	#echo -e "\033[31mThe input '$input' is NOT a valid IP:Port format. \033[0m"
fi
