#!/bin/bash

if [ ! $1 ];then
	echo -e "\033[31m需要指定一个文件\033[0m" ; exit
fi

file="$1"

echo -e "\033[32mbits(比特):\033[0m" #$(expr $(du -b $file) * 8)
echo -e "\033[32mbytes(字节):\033[0m" $(du -b $file) 
echo -e "\033[32mbytes(兆):\033[0m" $(du -h $file)
