#!/bin/bash
ScriptVersion="1.0"
set -e

# 使用场景：当你想要将你的ssh公钥发给你朋友，但是你朋友拿到了"id_rsa.pub"文件也不知道放在哪里，那么你可以将移动脚本的步骤些为一个脚本，然后将你的"id_rsa.pub"文件放在名为connect_ssh.sh脚本文件中，并告诉你朋友只需要执行connect_ssh.sh这个脚本文件就可以了，那么你的脚本文件可以是如下：
# move_to_home_dir.sh：
# ------------------------------------
# | mv id_rsa.pub $HOME/.ssh         |
# ------------------------------------
#
#然后使用命令：generate_self_archive move_to_home_dir.sh id_rsa.pub connect_ssh.sh
#
#将命令输出的文件发送给你朋友执行就可以完成移动文件的操作啦
# 不支持绝对路径的打包！！！！ 只能是在同一目录下的两个对象打包！！


#默认为zip压缩算法，Option: zip , tar
archive_mode="zip"

unset file
unset directory
unset archiveCMD
unset unarchiveCMD

main(){
  cat << EOF >  $output_bash_script
#!/bin/bash
set -e

#-------------------- Generate Content --------------------
ARCHIVE_START_LINE=\$(awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' \$0)
date=\$(date +"%Y%m%d%H%M%S")
tail -n+\${ARCHIVE_START_LINE} \$0 > ./temp_\$date.${archive_mode}
$unarchiveCMD temp_\$date.${archive_mode} > /dev/null && rm temp_\$date.${archive_mode}
EOF

echo "#-------------------- $1 --------------------" >> $output_bash_script
cat $bash_script_ab >> $output_bash_script
echo "#------------------------------------------" >> $output_bash_script
echo -e "exit 0 \n__ARCHIVE_BELOW__" >> $output_bash_script

date=$(date +"%Y%m%d%H%M%S")
$archiveCMD temp_$date.${archive_mode} $archive_obj > /dev/null
if [ ! -f "temp_$date.${archive_mode}" ];then
  echo -e "\033[31mNot fond file temp_$date.${archive_mode}\033[0m";exit
fi
cat temp_$date.${archive_mode} >> $output_bash_script && rm temp_$date.${archive_mode}
chmod +x $output_bash_script
echo -e "\033[32mOutput Bash script -> $output_bash_script\033[0m"
}

check_archive_mode(){
  if [ $archive_mode == "tar" ];then
    archive_mode="tar.gz"
  fi
  if [ $archive_mode == "tar.gz" ];then
    archiveCMD="tar -czf"
    unarchiveCMD="tar -xzf"
    check_cmd "tar"
  elif [ $archive_mode == "zip" ];then
    archiveCMD="zip -r"
    unarchiveCMD="unzip"
    check_cmd "zip"
    check_cmd "unzip"
  else
    echo "Unknown archive model"; exit;
  fi
}

#Checkout is install
check_cmd(){
  local obj=$1
  if [ ! -x "$(command -v $obj)" ];then
    echo "Not found $obj"
  fi
}


usage (){
  echo "Usage :  $(basename "$0") [options] [--] [shell_script(*.sh)] [archive_object(file|directory)] [Output script name](option)

  Options:
  -h, --help                  Display this message
  -d, --debug                 Debug model run
  -p, --posix                 Posix model parse shell command
  -v, --version               Display script version
  -f, --file FILE             Target file
  -m, --mode [zip|tar]        ARCHIVE_MODE
  -D, --directory DIRECTORY   Target directory"
}

while getopts ":hdpvf:m:D:-:" opt; do
  case "${opt}" in
    h) usage && exit 0;;
    d) set -x ;;
    p) set -o posix ;;
    v) echo "$0 -- Version $ScriptVersion"; exit ;;
    f) file=${OPTARG};;
    m) archive_mode=${OPTARG};;
    D) directory=${OPTARG};;
    -) case "${OPTARG}" in
      help) usage && exit 0;;
      debug)      set -x ;;
      posix)      set -o posix ;;
      version)    echo "$0 -- Version $ScriptVersion"; exit ;;
      file)       file=${!OPTIND}; OPTIND=$((OPTIND+1));;
      mode)       archive_mode=${!OPTIND}; OPTIND=$((OPTIND+1));;
      directory)  directory=${!OPTIND}; OPTIND=$((OPTIND+1));;
      *)          echo "Invalid option: --${OPTARG}" >&2 && exit 1;;
    esac;;
  :) echo "Option -${OPTARG} requires an argument." >&2 && exit 1;;
  *) echo "Invalid option: -${OPTARG}" >&2 && exit 1;;
esac
done
shift $((OPTIND-1))

if [ $# -lt 2 ];then usage;exit 0;fi

if [ ! -f "$1"  ];then
  echo -e "\033[31mNot found file $1\033[0m"; exit
fi

if [ ! -d "$2"  ];then
  if [ ! -f "$2"  ];then
    echo -e "\033[31mNot found file $2\033[0m"; exit
  fi
fi

bash_script="$(basename $1)"
archive_obj="$(basename $2)"
bash_script_ab="$1"
archive_obj_ab="$2"

if [ ! ${bash_script##*.} == "sh" ];then usage;exit 0;fi

check_archive_mode
if [ $3 ];then
  if [ "${3##*.}" == ""  ];then
    output_bash_script="$3.sh"
  else
    output_bash_script="$3"
  fi
else
  output_bash_script="${bash_script%.*}-with-${archive_obj%.*}-${archive_mode}.sh"
fi

main "$@"
