#!/bin/bash
set -e

echo "Are you sure you want to pull it? The original file will be overwritten! [Y/n]"

read is_ok

from_icloud() {
	pushd ~/Library/Mobile\ Documents/com~apple~CloudDocs
	cp -rv ./sh_foot/init.vim ~/.config/nvim/init.vim
	cp -rv ./sh_foot/markdown.snippets ~/.config/nvim/plugged/vim-snippets/UltiSnips/markdown.snippets
	cp -rv ./demo1 ~/Desktop/
	popd
	echo -e "\033[31m[🍺##########Done#############]"
}

from_github() {
	work_dirs=(
		#Config
		$HOME/sh_foot
		$HOME/Study
		$HOME/MD-Note
		#My Project
		$HOME/JPEGer
		$HOME/H264Decoder
		$HOME/H264Encoder
		$HOME/HEVCDecoder
		#Project 1
		$HOME/ffmpeg-4.4.2
		$HOME/x264-0.164.5
		$HOME/x265-3.6
		$HOME/dav1d-1.5.1
		$HOME/svtav1-3.1.2
		$HOME/ffmpeg-hevc-decoder-8.0
	)
	for in_dir in ${work_dirs[@]}; do
		if [ ! -d ${in_dir} ]; then
			echo "Not fond dir: ${in_dir}, skip it"
			continue
		fi
		pushd "${in_dir}"
		git pull
		popd
	done
	echo "Done!"
}

if [ "$is_ok" != "n" ]; then
	#from_icloud
	from_github
fi
