#!/bin/bash
set -e

echo "Are you sure you want to save? The original file will be overwritten![Y/n]"
read is_ok

to_icloud() {
	pushd ~/Library/Mobile\ Documents/com~apple~CloudDocs
	cp -vr ~/Desktop/demo1 ./                                                         #save demo1
	cp -vr ~/.config/nvim/init.vim ./sh_foot/                                         #save nvim config
	cp -vr ~/.config/nvim/plugged/vim-snippets/UltiSnips/markdown.snippets ./sh_foot/ #save markdown.snippets
	popd
	echo -e "\033[31m[🍺!!!!!!!!!!!Done!!!!!!!!!!!]"
}

to_github() {
	work_dirs=(
		#Config
		$HOME/sh_foot
		$HOME/Study
		$HOME/MD-Note
		#My Project
		$HOME/JPEGer
		$HOME/H264Decoder
		$HOME/H264Encoder
		$HOME/HEVCDecoder
		#Project 1
		$HOME/ffmpeg-4.4.2
		$HOME/x264-0.164.5
		$HOME/x265-3.6
		$HOME/dav1d-1.5.1
		$HOME/svtav1-3.1.2
		$HOME/ffmpeg-hevc-decoder-8.0
	)
	for in_dir in ${work_dirs[@]}; do
		if [ ! -d ${in_dir} ]; then
			echo "Not fond dir: ${in_dir}, skip it"
			continue
		fi
		pushd "${in_dir}"
		#git add . && git commit -m "Auto commit from[$0]" && git push
		#不执行add，为了防止提交了不完整的更改
		git commit -m "Auto commit from[$0]" && git push
		popd
	done
	echo "Done!"
}

if [ "$is_ok" != 'n' ]; then
	#to_icloud
	to_github
fi
