#!/bin/bash

set -e

on() {
	if [ "$(uname)" == "Linux" ]; then
		gsettings set org.gnome.system.proxy mode 'manual'
		gsettings set org.gnome.system.proxy.http port $http_proxy
		gsettings set org.gnome.system.proxy.http host "${ip}"
		gsettings set org.gnome.system.proxy.https port $http_proxy
		gsettings set org.gnome.system.proxy.https host "${ip}"
		gsettings set org.gnome.system.proxy.socks port "${socks_proxy}"
		gsettings set org.gnome.system.proxy.socks host "${ip}"
		gsettings set org.gnome.system.proxy ignore-hosts "['localhost', '127.0.0.0/8', '::1']"

	else
		#获取所有的网络服务
		network_services=$(networksetup -listallnetworkservices | tail -n +2 | grep -v '^*' | sed 's/ /_TODO_/g')
		for name in ${network_services}; do
			name=$(echo $name | sed 's/_TODO_/ /g')
			# 当前当前使用的网络服务，比如WiFi,USB iPhone
			if networksetup -getinfo "$name" | grep "^IP address: " >/dev/null; then
				# 设置代理
				networksetup -setwebproxy "$name" ${ip} $http_proxy && networksetup -setsecurewebproxy "$name" ${ip} $http_proxy
				# 启用代理
				networksetup -setwebproxystate "$name" on && networksetup -setsecurewebproxystate "$name" on
				# 查看
				networksetup -getwebproxy "$name" && networksetup -getsecurewebproxy "$name"
				break
			fi
		done
	fi
}

off() {
	if [ "$(uname)" == "Linux" ]; then
		gsettings set org.gnome.system.proxy mode 'none'
	else
		#关闭所有的网络服务
		network_services=$(networksetup -listallnetworkservices | tail -n +2 | sed 's/ /_TODO_/g')
		for name in ${network_services[@]}; do
			name=$(echo $name | sed 's/_TODO_/ /g')
			# 当前当前使用的网络服务，比如WiFi,USB iPhone
			if networksetup -getinfo "$name" | grep "^IP address: " >/dev/null; then
				networksetup -setwebproxystate "$name" off && networksetup -setsecurewebproxystate "$name" off
			fi
		done
	fi
}

auto() {
	if [ "$(uname)" == "Linux" ]; then
		gsettings set org.gnome.system.proxy mode 'auto'
	else
		echo "Mac OS ???"
		exit
	fi
}

opt="$1"
ip="$2"
http_proxy="$3"
socks_proxy="$4"

if [ ! "$ip" ]; then ip="127.0.0.1"; fi
if [ ! "$http_proxy" ]; then http_proxy="7890"; fi
if [ ! "$socks_proxy" ]; then socks_proxy="7891"; fi

case "${opt}" in
on) on ;;
off) off ;;
auto) auto ;;
*) echo "Invalid option: -${OPTARG} , Do you say '$(basename $0) on|off|auto' ?" >&2 && exit 1 ;;
esac
