#!/bin/bash

set -e

ScriptVersion="1.0"

TMPDIR="${TMPDIR:-/tmp}"
ssh_history="$HOME/.ssh_history"

unset ip
unset user
unset passwd
unset port
unset is_sftp

main() {
  init_input_info
  local date=$(date +"%Y%m%d%H%M%S")
  if [ -z "$port" ]; then
    port=22
  fi
  local tmp_date="${TMPDIR}/tmp_$date"
  echo "$ip $user $passwd $port" >>"$ssh_history"
  sort -u "$ssh_history" | sed '/^$/d' >"$tmp_date" && mv "$tmp_date" "$ssh_history"
  cat <<EOF >"$TMPDIR/load_ssh.expect"
#!/usr/bin/expect
set timeout 30

set ip   [lindex \$argv 0]
set name [lindex \$argv 1]
set pswd [lindex \$argv 2]
set port [lindex \$argv 3]
set ssh  [lindex \$argv 4]
set ssh_port_cmd  [lindex \$argv 5]

# Prefer password flow and disable GSSAPI to avoid some host-side auth stalls.
spawn \$ssh -o GSSAPIAuthentication=no -o PreferredAuthentications=password,keyboard-interactive \$ssh_port_cmd \$port \$name@\$ip
expect {
        "Are you sure you want to continue connecting*"
        {send "yes\n";exp_continue}
        -re "(P|p)assword:"
        {send "\$pswd\n"}
}
interact
EOF
  # cmd -> ssh | sftp
  if [ -n "$is_sftp" ]; then
    expect "$TMPDIR/load_ssh.expect" "$ip" "$user" "$passwd" "$port" sftp -P
  else
    expect "$TMPDIR/load_ssh.expect" "$ip" "$user" "$passwd" "$port" ssh -p
  fi
}

init_input_info() {
  if [ -z "$ip" ] || [ -z "$user" ] || [ -z "$passwd" ]; then
    # 没有输入连接信息
    if [ ! -f "$ssh_history" ]; then # 尝试本地获取历史信息
      echo -e "\033[31m Don't found user configure, Input you're $(basename "$0") -i [ip] -u [username] -p [passwd] \033[0m"
      exit 1
    else
      # 清理空行并去重
      local tmp_clean="${TMPDIR}/ssh_clean_$$"
      sort -u "$ssh_history" | sed '/^$/d' >"$tmp_clean" && mv "$tmp_clean" "$ssh_history"

      local -a hist_ips=() hist_users=() hist_passwds=() hist_ports=()
      while read -r h_ip h_user h_passwd h_port _; do
        [ -z "$h_ip" ] && continue
        hist_ips+=("$h_ip")
        hist_users+=("$h_user")
        hist_passwds+=("$h_passwd")
        hist_ports+=("${h_port:-22}")
      done <"$ssh_history"

      local total=${#hist_ips[@]}
      if [ "$total" -eq 0 ]; then
        echo -e "\033[31m Don't found user configure, Input you're $(basename "$0") -i [ip] -u [username] -p [passwd] \033[0m"
        exit 1
      elif [ "$total" -eq 1 ]; then
        ip="${hist_ips[0]}"
        user="${hist_users[0]}"
        passwd="${hist_passwds[0]}"
        port="${hist_ports[0]}"
      else
        echo -e "\033[33m存在多个连接信息：\033[0m"
        printf "%-14s %-18s %-14s %-6s\n" "SerialNumber" "IP" "User" "Port"
        for ((i = 0; i < total; i++)); do
          printf "%-14s %-18s %-14s %-6s\n" "$((i + 1))." "${hist_ips[i]}" "${hist_users[i]}" "${hist_ports[i]}"
        done
        echo -en "\033[33m请选择要连接的目标信息：\033[0m"
        read -r opt
        if [[ "$opt" =~ ^[0-9]+$ ]] && [ "$opt" -ge 1 ] && [ "$opt" -le "$total" ]; then
          local idx=$((opt - 1))
          ip="${hist_ips[idx]}"
          user="${hist_users[idx]}"
          passwd="${hist_passwds[idx]}"
          port="${hist_ports[idx]}"
        else
          echo -e "\033[31m输入错误，请输入对应的数字序号\033[0m"
          exit 1
        fi
      fi
    fi
  fi
}

usage() {
  echo "Usage :  $(basename "$0") [options] [--] argument-1 argument-2

  Options:
  -h, --help                  Display this message
  -d, --debug                 Debug model run
  -v, --version               Display script version
  -f, --file FILE             Target file
  -D, --directory DIRECTORY   Target directory
  -s, --show user             Show SSH user list
  -i, --ip address            SSH IP address
  -u, --user user             SSH User
  -p, --passwd password       SSH Password
  -P, --port port             SSH connect port"

}

while getopts ":hdvf:D:si:u:p:P:-:" opt; do
  case "${opt}" in
  h) usage && exit 0 ;;
  d) set -x ;;
  v)
    echo "$0 -- Version $ScriptVersion"
    exit
    ;;
  f) file=${OPTARG} ;;
  D) directory=${OPTARG} ;;
  s) cat $ssh_history && exit ;;
  i) ip=${OPTARG} ;;
  u) user=${OPTARG} ;;
  p) passwd=${OPTARG} ;;
  P) port=${OPTARG} ;;
  -) case "${OPTARG}" in
    help) usage && exit 0 ;;
    debug) set -x ;;
    version)
      echo "$0 -- Version $ScriptVersion"
      exit
      ;;
    file)
      file=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    directory)
      directory=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    ip)
      ip=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    user)
      user=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    passwd)
      passwd=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    sftp)
      is_sftp=1
      OPTIND=$((OPTIND + 1))
      ;;
    *) echo "Invalid option: --${OPTARG}" >&2 && exit 1 ;;
    esac ;;
  :) echo "Option -${OPTARG} requires an argument." >&2 && exit 1 ;;
  *) echo "Invalid option: -${OPTARG}" >&2 && exit 1 ;;
  esac
done
shift $((OPTIND - 1))

main "$@"
