#!/bin/bash

set -e

ScriptVersion="1.0"

TMPDIR="${TMPDIR:-/tmp}"
ssh_history="$HOME/.ssh_history"

unset ip
unset user
unset passwd
unset port

main() {
  obj="$1"
  init_input_info
  if [[ -f "$obj" || -d "$obj" ]]; then
    # 本地存在则为本地文件，表示要上传到服务器文件
    scp_up
  else
    # 本地都不存在则为服务器文件，表示要下载服务器文件在本地
    scp_down
  fi
}

init_input_info() {
  if [ -z "$ip" ] || [ -z "$user" ] || [ -z "$passwd" ]; then
    # 没有输入连接信息
    if [ ! -f "$ssh_history" ]; then # 尝试本地获取历史信息
      echo -e "\033[31m Don't found user configure, Input you're $(basename "$0") -i [ip] -u [username] -p [passwd] \033[0m"
      exit 1
    else
      # 清理空行并去重
      local tmp_clean="${TMPDIR}/ssh_clean_$$"
      sort -u "$ssh_history" | sed '/^$/d' >"$tmp_clean" && mv "$tmp_clean" "$ssh_history"

      local -a hist_ips=() hist_users=() hist_passwds=() hist_ports=()
      while read -r h_ip h_user h_passwd h_port _; do
        [ -z "$h_ip" ] && continue
        hist_ips+=("$h_ip")
        hist_users+=("$h_user")
        hist_passwds+=("$h_passwd")
        hist_ports+=("${h_port:-22}")
      done <"$ssh_history"

      local total=${#hist_ips[@]}
      if [ "$total" -eq 0 ]; then
        echo -e "\033[31m Don't found user configure, Input you're $(basename "$0") -i [ip] -u [username] -p [passwd] \033[0m"
        exit 1
      elif [ "$total" -eq 1 ]; then
        ip="${hist_ips[0]}"
        user="${hist_users[0]}"
        passwd="${hist_passwds[0]}"
        port="${hist_ports[0]}"
      else
        echo -e "\033[33m存在多个连接信息：\033[0m"
        printf "%-14s %-18s %-14s %-6s\n" "SerialNumber" "IP" "User" "Port"
        for ((i = 0; i < total; i++)); do
          printf "%-14s %-18s %-14s %-6s\n" "$((i + 1))." "${hist_ips[i]}" "${hist_users[i]}" "${hist_ports[i]}"
        done
        echo -en "\033[33m请选择要连接的目标信息：\033[0m"
        read -r opt
        if [[ "$opt" =~ ^[0-9]+$ ]] && [ "$opt" -ge 1 ] && [ "$opt" -le "$total" ]; then
          local idx=$((opt - 1))
          ip="${hist_ips[idx]}"
          user="${hist_users[idx]}"
          passwd="${hist_passwds[idx]}"
          port="${hist_ports[idx]}"
        else
          echo -e "\033[31m输入错误，请输入对应的数字序号\033[0m"
          exit 1
        fi
      fi
    fi
  fi
}

scp_up() {
  echo -e "\033[32mUpload File\033[0m"

  cat <<EOF >$TMPDIR/scp_up.expect
#!/usr/bin/expect

set timeout -1

set file [lindex \$argv 0]
set ip   [lindex \$argv 1]
set name [lindex \$argv 2]
set pswd [lindex \$argv 3]
set port [lindex \$argv 4]

spawn scp -r -P \$port \$file \$name@\$ip:.
expect {
    timeout {
        puts "Error: Timeout waiting for prompt."
        exit 1
    }
    "yes/no" {
        send "yes\n"
        exp_continue
    }
    "assword:" {
        send "\$pswd\n"
        exp_continue
    }
    eof {
        # File transfer completed
    }
}
#expect eof
#interact
EOF

  expect $TMPDIR/scp_up.expect $obj $ip $user $passwd $port
}

scp_down() {
  echo -e "\033[32mDownload File\033[0m"

  cat <<EOF >$TMPDIR/scp_down.expect
#!/usr/bin/expect

set timeout -1

set file [lindex \$argv 0]
set ip   [lindex \$argv 1]
set name [lindex \$argv 2]
set pswd [lindex \$argv 3]
set port [lindex \$argv 4]

spawn scp -r -P \$port \$name@\$ip:\$file .
expect {
    timeout {
        puts "Error: Timeout waiting for prompt."
        exit 1
    }
    "yes/no" {
        send "yes\n"
        exp_continue
    }
    "assword:" {
        send "\$pswd\n"
        exp_continue
    }
    eof {
        # File transfer completed
    }
}
#expect eof
#interact
EOF

  expect $TMPDIR/scp_down.expect $obj $ip $user $passwd $port
}

usage() {
  echo "Usage :  $(basename "$0") [options] [--] argument-1 argument-2

  Options:
  -h, --help                  Display this message
  -d, --debug                 Debug model run
  -v, --version               Display script version
  -f, --file FILE             Target file
  -D, --directory DIRECTORY   Target directory
  -s, --show user             Show SSH user list
  -i, --ip address            SSH IP address
  -u, --user user             SSH User
  -p, --passwd password       SSH Password
  -P, --port port             SSH connect port"

}

while getopts ":hdvf:D:si:u:p:P:-:" opt; do
  case "${opt}" in
  h) usage && exit 0 ;;
  d) set -x ;;
  v)
    echo "$0 -- Version $ScriptVersion"
    exit
    ;;
  f) file=${OPTARG} ;;
  D) directory=${OPTARG} ;;
  s) cat $ssh_history && exit ;;
  i) ip=${OPTARG} ;;
  u) user=${OPTARG} ;;
  p) passwd=${OPTARG} ;;
  P) port=${OPTARG} ;;
  -) case "${OPTARG}" in
    help) usage && exit 0 ;;
    debug) set -x ;;
    version)
      echo "$0 -- Version $ScriptVersion"
      exit
      ;;
    file)
      file=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    directory)
      directory=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    ip)
      ip=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    user)
      user=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    passwd)
      passwd=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    port)
      port=${!OPTIND}
      OPTIND=$((OPTIND + 1))
      ;;
    *) echo "Invalid option: --${OPTARG}" >&2 && exit 1 ;;
    esac ;;
  :) echo "Option -${OPTARG} requires an argument." >&2 && exit 1 ;;
  *) echo "Invalid option: -${OPTARG}" >&2 && exit 1 ;;
  esac
done
shift $((OPTIND - 1))

if [ ! $1 ]; then
  echo -e "\033[31m Need target file/directory \033[0m"
  exit
fi

main "$@"
