#!/bin/bash

if [ "$(uname)" == "Linux" ];then
	systemctl $@
	exit
fi

options="$1"     #start|stop|restart
server_name="$2" #$HOME/Library/LaunchAgents/com.rl.clash.plist

if [ -z "$options" ] || [ -z "$server_name" ]; then
	echo "Options or Server name is empty"
	exit
fi

if [ "$options" == "start" ]; then
	launchctl bootstrap gui/$(id -u) $server_name
elif [ "$options" == "stop" ]; then
	launchctl bootout gui/$(id -u) $server_name
elif [ "$options" == "restart" ]; then
	launchctl bootout gui/$(id -u) $server_name
	launchctl bootstrap gui/$(id -u) $server_name
else
	echo "Server name is error"
fi
