#!/bin/bash

set -e

ScriptVersion="2.0"
screen_info_file="$HOME/.screen_info"
window_name=":ACTIVE:"
key=""
file=""
directory=""
second_screen=""

convert_to_int() {
	local n=$1
	if [ -z "$n" ]; then
		echo 0
	else
		echo "$n"
	fi
}

usage() {
	echo "Usage: $(basename "$0") [options]

Options:
  -h, --help        Display this message
  -v, --version     Display script version
  -p <screen>       Screen index, e.g. 1 or 2
  -w <window>       Window title, default is :ACTIVE:
  -l                Move window to left half
  -r                Move window to right half
  -u                Move window to top-left
  -i                Move window to top-right
  -j                Move window to bottom-left
  -k                Move window to bottom-right
  -t                Move window to top half
  -d                Move window to bottom half
  -c                Center window
  -m                Maximize window"
}

is_wayland_gnome_session() {
	[ "${XDG_SESSION_TYPE:-}" = "wayland" ] &&
		gdbus introspect --session --dest org.gnome.Shell --object-path /org/gnome/Shell >/dev/null 2>&1
}

wayland_extension_available() {
	gdbus introspect --session \
		--dest org.gnome.Shell \
		--object-path /io/github/hi/UbuntuMoveWindows >/dev/null 2>&1
}

wayland_main() {
	if [ -z "$key" ]; then
		usage
		exit 1
	fi

	if wayland_extension_available; then
		local monitor_index=-1
		if [ -n "$second_screen" ] && echo "$second_screen" | grep -Eq '^[0-9]+$' && [ "$second_screen" -ge 1 ]; then
			monitor_index=$((second_screen - 1))
		fi

		gdbus call --session \
			--dest org.gnome.Shell \
			--object-path /io/github/hi/UbuntuMoveWindows \
			--method io.github.hi.UbuntuMoveWindows.ApplyAction \
			-- \
			"$key" "$window_name" "$monitor_index" >/dev/null
		return
	fi

	echo "Wayland backend is installed but GNOME Shell has not loaded it in the current session yet." >&2
	echo "Please log out and log back in once, then run this command again." >&2
	exit 1
}

get_dock_height() {
	local dock_height=0

	if command -v gsettings >/dev/null 2>&1; then
		if gsettings get org.gnome.shell.extensions.dash-to-dock dock-fixed >/dev/null 2>&1; then
			dock_height=$(gsettings get org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 2>/dev/null | awk '{print $1}')
			if [ -n "$dock_height" ] && [ "$dock_height" -gt 0 ]; then
				echo $((dock_height + 10))
				return
			fi
		fi
	fi

	local dock_window
	dock_window=$(xwininfo -root -tree 2>/dev/null | grep -iE '(dock|panel|gnome-shell)' | head -1 | awk '{print $1}')
	if [ -n "$dock_window" ]; then
		dock_height=$(xwininfo -id "$dock_window" 2>/dev/null | awk '/Height/ {print $2}')
		if [ -n "$dock_height" ] && [ "$dock_height" -gt 0 ]; then
			echo "$dock_height"
			return
		fi
	fi

	echo 0
}

get_dock_position() {
	echo "bottom"
}

init_info() {
	work_area=$(xprop -root _NET_WORKAREA | sed 's/_NET_WORKAREA(CARDINAL) = //; s/,//g')
	x=$(echo "$work_area" | awk '{print $1}')
	y=$(echo "$work_area" | awk '{print $2}')
	wid=$(echo "$work_area" | awk '{print $3}')
	hei=$(echo "$work_area" | awk '{print $4}')

	dock_height=$(get_dock_height)
	dock_position=$(get_dock_position)

	screen_count=$(xrandr 2>/dev/null | grep ' connected' | wc -l)
	if [ "$screen_count" = "1" ]; then
		half_wid=$(expr "$wid" / 2)
		half_hei=$(expr "$hei" / 2)
		primary_screen_width=$wid
		primary_screen_height=$hei
		secondary_screen_width=0
		secondary_screen_height=0
	elif [ "$screen_count" = "2" ]; then
		primary_screen_info=$(xrandr 2>/dev/null | grep ' connected' | grep 'primary')
		primary_screen_width=$(echo "$primary_screen_info" | awk '{print $4}' | awk -F "x" '{print $1}')
		primary_screen_height=$(echo "$primary_screen_info" | awk '{print $4}' | awk -F "x" '{print $2}' | awk -F "+" '{print $1}')

		if [ "$dock_position" = "bottom" ] && [ "$dock_height" -gt 0 ]; then
			primary_screen_height=$((primary_screen_height - dock_height))
		fi

		secondary_screen_info=$(xrandr 2>/dev/null | grep ' connected' | grep -v 'primary')
		secondary_screen_width=$(echo "$secondary_screen_info" | awk '{print $3}' | awk -F "x" '{print $1}')
		secondary_screen_height=$(echo "$secondary_screen_info" | awk '{print $3}' | awk -F "x" '{print $2}' | awk -F "+" '{print $1}')

		if [ "$primary_screen_width" = "$secondary_screen_width" ] && [ "$primary_screen_height" = "$secondary_screen_height" ]; then
			half_wid=$(expr "$wid" / 4)
			half_hei=$(expr "$hei" / 2)
		else
			half_wid=$(expr "$primary_screen_width" / 2)
			half_hei=$(expr "$primary_screen_height" / 2)
		fi
	else
		echo "TODO: more than two screens are not supported on the X11 backend." >&2
		exit 1
	fi

	echo all_width:$(convert_to_int "$wid") >"$screen_info_file"
	echo all_height:$(convert_to_int "$hei") >>"$screen_info_file"
	echo primary_screen_width:$(convert_to_int "$primary_screen_width") >>"$screen_info_file"
	echo primary_screen_height:$(convert_to_int "$primary_screen_height") >>"$screen_info_file"
	echo secondary_screen_width:$(convert_to_int "$secondary_screen_width") >>"$screen_info_file"
	echo secondary_screen_height:$(convert_to_int "$secondary_screen_height") >>"$screen_info_file"
	echo half_wid:$(convert_to_int "$half_wid") >>"$screen_info_file"
	echo half_hei:$(convert_to_int "$half_hei") >>"$screen_info_file"
	echo dock_height:$(convert_to_int "$dock_height") >>"$screen_info_file"
	echo dock_position:$dock_position >>"$screen_info_file"
	echo x:$x >>"$screen_info_file"
	echo y:$y >>"$screen_info_file"
}

read_database_info() {
	wid=$(grep '^all_width:' "$screen_info_file" | awk -F ":" '{print $2}')
	hei=$(grep '^all_height:' "$screen_info_file" | awk -F ":" '{print $2}')
	primary_screen_width=$(grep '^primary_screen_width:' "$screen_info_file" | awk -F ":" '{print $2}')
	primary_screen_height=$(grep '^primary_screen_height:' "$screen_info_file" | awk -F ":" '{print $2}')
	secondary_screen_width=$(grep '^secondary_screen_width:' "$screen_info_file" | awk -F ":" '{print $2}')
	secondary_screen_height=$(grep '^secondary_screen_height:' "$screen_info_file" | awk -F ":" '{print $2}')
	half_wid=$(grep '^half_wid:' "$screen_info_file" | awk -F ":" '{print $2}')
	half_hei=$(grep '^half_hei:' "$screen_info_file" | awk -F ":" '{print $2}')
	dock_height=$(grep '^dock_height:' "$screen_info_file" | awk -F ":" '{print $2}')
	dock_position=$(grep '^dock_position:' "$screen_info_file" | awk -F ":" '{print $2}')
	x=$(grep '^x:' "$screen_info_file" | awk -F ":" '{print $2}')
	y=$(grep '^y:' "$screen_info_file" | awk -F ":" '{print $2}')
}

check_current_position() {
	current_position=$(xdotool getactivewindow getwindowgeometry | awk -F '[:, ]+' '/Position/ {print $3}')
	offset=0
	if [ "$primary_screen_width" != 0 ]; then
		if [ "$current_position" -le "$primary_screen_width" ]; then
			screen_wid=$primary_screen_width
			screen_hei=$primary_screen_height
			half_wid=$(expr "$screen_wid" / 2)
			half_hei=$(expr "$screen_hei" / 2)
		else
			screen_wid=$secondary_screen_width
			screen_hei=$secondary_screen_height
			half_wid=$(expr "$screen_wid" / 2)
			half_hei=$(expr "$screen_hei" / 2)
			offset=$(expr "$primary_screen_width" + 10)
		fi
	else
		screen_wid=$wid
		screen_hei=$hei
		half_wid=$(expr "$screen_wid" / 2)
		half_hei=$(expr "$screen_hei" / 2)
	fi
}

get_current_windows_size() {
	windows_wid=$(xwininfo -id "$(xdotool getactivewindow)" | awk '/Width/ {print $2}')
	windows_hei=$(xwininfo -id "$(xdotool getactivewindow)" | awk '/Height/ {print $2}')
	wmctrl -r "$window_name" -e 2,$(expr $(expr "$screen_wid" - "$windows_wid") / 2 + "$offset"),$(expr $(expr "$screen_hei" - "$windows_hei") / 2 + "$y"),$windows_wid,$windows_hei
}

x11_main() {
	if [ -z "$key" ]; then
		usage
		exit 1
	fi

	if [ -f "$screen_info_file" ]; then
		read_database_info
	else
		init_info
	fi
	check_current_position

	if [ "$key" = "left" ]; then
		wmctrl -r "$window_name" -e 2,$offset,$y,$half_wid,$screen_hei
	elif [ "$key" = "right" ]; then
		wmctrl -r "$window_name" -e 2,$(expr "$half_wid" + "$offset"),$y,$half_wid,$screen_hei
	elif [ "$key" = "u" ]; then
		wmctrl -r "$window_name" -e 2,$offset,$y,$half_wid,$half_hei
	elif [ "$key" = "i" ]; then
		wmctrl -r "$window_name" -e 2,$(expr "$half_wid" + "$offset"),$y,$half_wid,$half_hei
	elif [ "$key" = "j" ]; then
		wmctrl -r "$window_name" -e 2,$offset,$(expr "$half_hei" + "$y"),$half_wid,$half_hei
	elif [ "$key" = "k" ]; then
		wmctrl -r "$window_name" -e 2,$(expr "$half_wid" + "$offset"),$(expr "$half_hei" + "$y"),$half_wid,$half_hei
	elif [ "$key" = "top" ]; then
		wmctrl -r "$window_name" -e 2,$offset,$y,$screen_wid,$half_hei
	elif [ "$key" = "down" ]; then
		wmctrl -r "$window_name" -e 2,$offset,$(expr "$half_hei" + "$y"),$screen_wid,$half_hei
	elif [ "$key" = "center" ]; then
		get_current_windows_size
	elif [ "$key" = "max" ]; then
		wmctrl -r "$window_name" -e 2,0,$y,$wid,$hei
	fi
}

main() {
	if is_wayland_gnome_session; then
		wayland_main
	else
		x11_main
	fi
}

while getopts ":hp:vlruijktdcmw:D:-:" opt; do
	case "${opt}" in
	h) usage && exit 0 ;;
	p) second_screen="${OPTARG}" ;;
	v)
		echo "$0 -- Version $ScriptVersion"
		exit 0
		;;
	l) key="left" ;;
	r) key="right" ;;
	u) key="u" ;;
	i) key="i" ;;
	j) key="j" ;;
	k) key="k" ;;
	t) key="top" ;;
	d) key="down" ;;
	c) key="center" ;;
	m) key="max" ;;
	w) window_name="${OPTARG}" ;;
	D) directory=${OPTARG} ;;
	-) case "${OPTARG}" in
		help) usage && exit 0 ;;
		version)
			echo "$0 -- Version $ScriptVersion"
			exit 0
			;;
		file)
			file=${!OPTIND}
			OPTIND=$((OPTIND + 1))
			;;
		directory)
			directory=${!OPTIND}
			OPTIND=$((OPTIND + 1))
			;;
		*) echo "Invalid option: --${OPTARG}" >&2 && exit 1 ;;
		esac ;;
	:) echo "Option -${OPTARG} requires an argument." >&2 && exit 1 ;;
	*) echo "Invalid option: -${OPTARG}" >&2 && exit 1 ;;
	esac
done
shift $((OPTIND - 1))

main "$@"
