#!/bin/bash

set -e

TMP=$TMPDIR
#vim=vim
vim=nvim

file="$@"
#  如果只是输入了vimm则进入判断 #
if [ "$file" == "" ]; then
	if [ -f Session.vim ]; then
		#  1. 使用Session.vim文件 #
		file="-S Session.vim"
		echo "Use Session.vim"
	else
		#  2. 使用当前目录所有头文件、源代码文件 #
		file=$(find . -type f -name "*.cpp" -or -name "*.hpp" -or -name "*.c" -or -name "*.h")
		echo "Use (*.cpp *.hpp)"
	fi
fi

if [ $vim == "nvim" ]; then
	config_file="$HOME/.config/nvim/init.vim"
else
	config_file="$HOME/.vimrc"
fi

if [ ! -f $config_file ]; then
	echo -e "\033[31mNot found the $config_file\033[0m"
	exit
fi
sed 's/let g:is_vim_studio=0/let g:is_vim_studio=1/' $config_file >$TMP/init_studio.vim

#$vim -u $TMP/init_studio.vim -c "let \$MYVIMRC = expand('\$config_file') | execute 'lua require(\"notify\")(\"Welcome to VIM-Studio\")'" $file
$vim -u $TMP/init_studio.vim -c "let \$MYVIMRC = expand('$config_file')" $file
